name: Deploy to GitHub Pages via angular-cli-ghpages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   build-and-deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Use Node.js 14.x
       uses: actions/setup-node@v1
       with:
         node-version: 14.x

     - name: Prepare and deploy
       env:
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
       run: |
         npm install
         npm run ng -- deploy --base-href=/need-for-drive/  --name="Displayed Username" --email=your.mail@example.org
